# Generated by Django 2.2.6 on 2019-11-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20191105_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='crn',
            field=models.CharField(db_index=True, default='123456', max_length=10),
            preserve_default=False,
        ),
    ]
