# Generated by Django 2.1.7 on 2019-09-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='corequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='distribution_of_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
