# Generated by Django 2.1.7 on 2019-09-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190922_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('build', models.CharField(max_length=4)),
                ('dept', models.CharField(max_length=5)),
                ('meeting_days', models.CharField(max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('instructor', models.CharField(max_length=100)),
                ('meetings', models.ManyToManyField(to='scraper.Meeting')),
            ],
        ),
    ]
