# Generated by Django 2.1.7 on 2019-09-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_meeting_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='build',
            new_name='building',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(default='AAAA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.CharField(default='BBBB', max_length=4),
            preserve_default=False,
        ),
    ]
