# Generated by Django 2.1.7 on 2019-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20190922_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='dept',
        ),
        migrations.AddField(
            model_name='meeting',
            name='crn',
            field=models.CharField(db_index=True, default='00000', max_length=20),
            preserve_default=False,
        ),
    ]
