# Generated by Django 2.1.7 on 2019-09-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20190922_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='crn',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
