# Generated by Django 2.1.7 on 2019-09-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20190922_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='crn',
        ),
        migrations.AddField(
            model_name='section',
            name='id',
            field=models.CharField(default=0, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
