# Generated by Django 2.1.7 on 2019-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_auto_20190928_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course_num',
            field=models.CharField(db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_num',
            field=models.CharField(db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='term_code',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='subject',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
