# Generated by Django 2.1.7 on 2019-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_auto_20190928_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='course_num',
            field=models.CharField(db_index=True, default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='section_num',
            field=models.CharField(db_index=True, default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='term_code',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
