# Generated by Django 2.1.7 on 2019-09-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_auto_20190928_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='currentEnrolled',
            new_name='current_enrolled',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='maxEnrollment',
            new_name='max_enrollment',
        ),
    ]
