# Generated by Django 2.2.6 on 2019-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_auto_20190928_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='building',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
