# Generated by Django 2.2.6 on 2019-10-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_auto_20191023_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
